### ISSUE TITLE
Unable to run the project

### ISSUE THREAD

**Issue by pcmakine** [presemo/presemo-v4#2]
I am unable to run the project on a Windows machine.
I tried running npm rebuild and node app/index.js and the error I got was:

events.js:85   throw er; // Unhandled 'error'event   ^   Error: ENOENT, open 'D:\IntecProject\presemo-v4\db\objects.dirty'  at Error (native)  

I tried creating a folder db at the project root and created two empty files objects.dirty and session.dirty. Now node app/index.js goes further but gives following error:

D:\IntecProject\presemo-v4\app\lib\BlockBuilderSync.js:975                                                          throw e;                                                                                                          ^                                                                                             Error: EPERM, operation not permitted 'D:\IntecProject\presemo-v4\public\assets\pollplus'                       at Error (native)                                                                                           at Object.fs.symlinkSync (fs.js:848:18)                                                                     at ensureSymlink (D:\IntecProject\presemo-v4\app\lib\BlockBuilderSync.js:967:10)                            at D:\IntecProject\presemo-v4\app\node_modules\async\lib\async.js:595:21                                    at D:\IntecProject\presemo-v4\app\node_modules\async\lib\async.js:235:13                                    at iterate (D:\IntecProject\presemo-v4\app\node_modules\async\lib\async.js:142:13)                          at D:\IntecProject\presemo-v4\app\node_modules\async\lib\async.js:153:25                                    at D:\IntecProject\presemo-v4\app\node_modules\async\lib\async.js:237:17                                    at D:\IntecProject\presemo-v4\app\node_modules\async\lib\async.js:600:34                                    at done (D:\IntecProject\presemo-v4\app\node_modules\async\lib\async.js:128:19)

**Comment by pcmakine** [comment]
Actually it works if you run the command line with administrator rights and then run the project

**Comment by plievone** [comment]
Hi! Thanks for trying it out in windows, and good to hear that it works. I now added the db dir to git repo to prevent that startup error. There might still be some permission problems in your setup, perhaps node may have been installed/run with different users/permissions. Presemo touches repo/build, repo/db, repo/public/assets and if one runs with different permissions the generated files may then be inaccessible to later runs with different permissions. Perhaps best to start with a clean git clone.

If you need to change the port in config.json to a lower port that needs elevated permissions, it is better to run nginx or some other proxy in front of it and keep presemo in higher ports.

Feel free to reopen the issue if you have problems!
